appname: "App::Socialdump"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"

plugins:
    DBIC:
        default:
            dsn: 'dbi:SQLite:dbname=database.db'
            schema_class: 'App::Socialdump::Schema'
            options:
                sqlite_unicode: 1
